#!/usr/bin/env python3
"""Tables and figures for the Qwen3-8B multi-constraint experiment (QWEN3_8B_PLAN.md).

Reads results/qwen3_8b/eval/<label>/graded.jsonl for base, S1-60, S1-final, T3-60, T3-final, Q5-final and the
Qwen3.5-9B summaries in results/multi_eval/ for the cross-model comparison. Writes QWEN3_8B_RESULTS.md and
figures/q3_8b_*.png.
"""
from __future__ import annotations
import json, math, statistics as st, sys
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[1]
SURF, INK, INK2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"
C = {"base": "#c3c2b7", "S1": "#86b6ef", "T3": "#104281", "Q5": "#eb6834"}
LABS = ["base", "S1-60", "S1-final", "T3-60", "T3-final", "Q5-final"]
FINAL = ["base", "S1-final", "T3-final", "Q5-final"]
plt.rcParams.update({"figure.facecolor": SURF, "axes.facecolor": SURF, "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED,
                     "font.size": 9.5, "axes.spines.top": False, "axes.spines.right": False, "savefig.dpi": 150, "savefig.facecolor": SURF})

def arm(l): return l.split("-")[0]
G = {l: [json.loads(x) for x in open(REPO / f"results/qwen3_8b/eval/{l}/graded.jsonl")] for l in LABS}
def rows(l, suite, level=None, held=None, mode=None):
    return [r for r in G[l] if r["suite"] == suite and (level is None or r["level"] == level) and (held is None or bool(r["held_out"]) == held) and (mode is None or r["constraints"][0] == mode)]
def joint(rs):
    ok = [r for r in rs if r["think_status"] == "ok" and r["joint"] is not None]
    if not ok: return None, 0
    p = sum(r["joint"] for r in ok) / len(ok); return p, len(ok)
def ci80(p, n): return 1.2816 * math.sqrt(p * (1 - p) / n) if n else 0
def per_bin(rs, m):
    v = [r["per_binary"][m] for r in rs if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def per_cont(rs, m):
    v = [r["per_continuous"][m] for r in rs if r["think_status"] == "ok" and r["per_continuous"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def acc(rs): return sum(bool(r["correct"]) for r in rs) / len(rs) if rs else None
def cont_macro(l, level=1, exclude=None):
    """CoTControl continuous, macro over modes (k=1) — comparable to MULTI_CONSTRAINT_FINDINGS.md finding 4b."""
    vals = []
    for m in sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)}):
        if m == exclude: continue
        v, n = per_cont(rows(l, "cotcontrol_multi", level, mode=m), m)
        if v is not None: vals.append(v)
    return sum(vals) / len(vals) if vals else None

md = ["# Multi-constraint SFT on Qwen3-8B: results\n", "*Generated by `scripts/report_qwen3_8b.py`. Joint = every constraint in the prompt satisfied, binary, % of gradeable (closed think block) rollouts; ± = 80 % Wald interval.*\n"]
P = md.append
def pct(p, n): return "—" if p is None else f"{100*p:.1f} ± {100*ci80(p,n):.1f}"

P("\n## Joint binary compliance by level\n")
P("| suite | level | " + " | ".join(LABS) + " |"); P("|---|---|" + "---:|" * len(LABS))
for suite, name in (("reasonif_multi", "ReasonIF"), ("cotcontrol_multi", "CoTControl")):
    for lvl in (1, 3, 5, 6):
        for held in (None, True):
            cells = []
            for l in LABS:
                rs = rows(l, suite, lvl, held); p, n = joint(rs); cells.append(pct(p, n) if rs else "—")
            if all(c == "—" for c in cells): continue
            P(f"| {name} | k={lvl}{' held-out' if held else ''} | " + " | ".join(cells) + " |")
P("\n## Accuracy on the k=1 prompts (%)\n")
P("| suite | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for suite, name in (("reasonif_multi", "ReasonIF"), ("cotcontrol_multi", "CoTControl")):
    P(f"| {name} | " + " | ".join(f"{100*acc(rows(l, suite, 1)):.0f}" for l in LABS) + " |")
P("\n## Per-constraint compliance on single-constraint prompts (binary % / continuous)\n")
P("| constraint | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for suite in ("reasonif_multi", "cotcontrol_multi"):
    for m in sorted({r["constraints"][0] for r in rows("base", suite, 1)}):
        cells = []
        for l in LABS:
            b, nb = per_bin(rows(l, suite, 1, mode=m), m); c, nc = per_cont(rows(l, suite, 1, mode=m), m)
            cells.append(("—" if b is None else f"{100*b:.0f}") + ("" if c is None else f" / {c:.2f}"))
        P(f"| {suite[:3]}/{m} | " + " | ".join(cells) + " |")
P("\n## CoTControl continuous macro over the ten modes (k=1)\n")
P("| | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
P("| all ten modes | " + " | ".join(f"{cont_macro(l):.2f}" for l in LABS) + " |")
P("| excluding uppercase_thinking | " + " | ".join(f"{cont_macro(l, exclude='uppercase_thinking'):.2f}" for l in LABS) + " |")
P("\n## Per-constraint binary by number of rules in the prompt (ReasonIF, %, step-final arms)\n")
P("| constraint | " + " | ".join(f"{l} k=1/3/5" for l in FINAL) + " |"); P("|---|" + "---:|" * len(FINAL))
for m in sorted({r["constraints"][0] for r in rows("base", "reasonif_multi", 1)}):
    cells = []
    for l in FINAL:
        vals = []
        for lvl in (1, 3, 5):
            v = [r["per_binary"][m] for r in rows(l, "reasonif_multi", lvl) if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]
            vals.append(f"{100*sum(v)/len(v):.0f}" if v else "—")
        cells.append(" / ".join(vals))
    P(f"| {m} | " + " | ".join(cells) + " |")
P("\n## Per-mode binary inside CoTControl combinations (%, gradeable rollouts containing the mode)\n")
P("| level | checkpoint | " + " | ".join(m for m in sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)})) + " |")
modes_cc = sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)}); P("|---|---|" + "---:|" * len(modes_cc))
for lvl in (3, 6):
    for l in FINAL:
        per = defaultdict(list)
        for r in rows(l, "cotcontrol_multi", lvl):
            if r["think_status"] != "ok": continue
            for m, b in r["per_binary"].items():
                if b is not None: per[m].append(b)
        P(f"| k={lvl} | {l} | " + " | ".join(f"{100*sum(per[m])/len(per[m]):.0f}" if per[m] else "—" for m in modes_cc) + " |")
P("\n## Trace status\n")
P("| | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
P("| rollouts | " + " | ".join(str(len(G[l])) for l in LABS) + " |")
P("| truncated at 32k | " + " | ".join(str(sum(r['truncated'] for r in G[l])) for l in LABS) + " |")
P("| empty think block | " + " | ".join(str(sum(r['think_status'] == 'empty' for r in G[l])) for l in LABS) + " |")
P("| median completion tokens, CoTControl k=1 | " + " | ".join(str(int(st.median(r['completion_tokens'] for r in rows(l, 'cotcontrol_multi', 1)))) for l in LABS) + " |")

# ---------------------------------------------------------------- figures
def style(ax): ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)

# Fig 1: ReasonIF joint by level, step-final arms, seen vs held-out at k=3
fig, ax = plt.subplots(figsize=(7.5, 4))
for l in FINAL:
    pts = [(lvl, 100 * joint(rows(l, "reasonif_multi", lvl))[0]) for lvl in (1, 3, 5)]
    ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=C[arm(l)], markeredgecolor=SURF, label=l)
    ph, nh = joint(rows(l, "reasonif_multi", 3, held=True))
    if ph is not None: ax.plot([3.12], [100 * ph], marker="D", ms=6, color=C[arm(l)], ls="", markeredgecolor=SURF)
ax.plot([], [], marker="D", ms=6, color=INK2, ls="", label="◆ held-out triples only"); ax.set_xticks([1, 3, 5]); ax.set_xticklabels(["1 constraint", "3", "5"]); ax.set_ylabel("joint compliance, %"); style(ax)
ax.set_title("Qwen3-8B, ReasonIF-side: joint binary compliance vs number of constraints (step-final)\nQ5 was trained on 5-constraint prompts only; ◆ = the 4 held-out triples", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.14)); ax.set_ylim(0, 60); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_joint_reasonif.png", bbox_inches="tight"); plt.close(fig)

# Fig 2: CoTControl k=1 joint binary per checkpoint (bars), with the k=3/k=6 zeros noted
fig, ax = plt.subplots(figsize=(7.5, 3.8))
vals = [joint(rows(l, "cotcontrol_multi", 1)) for l in LABS]
ax.bar(range(len(LABS)), [100 * v for v, _ in vals], color=[C[arm(l)] for l in LABS], width=0.62, edgecolor=SURF)
for i, (v, n) in enumerate(vals): ax.text(i, 100 * v + 0.4, f"{100*v:.1f}", ha="center", fontsize=9, color=INK2)
ax.set_xticks(range(len(LABS))); ax.set_xticklabels(LABS); ax.set_ylabel("joint compliance, %"); style(ax); ax.set_ylim(0, 16)
ax.set_title("Qwen3-8B, CoTControl-side transfer: joint binary compliance on single-mode prompts\n(k=3 and k=6 prompts: 0 % for every checkpoint)", loc="left", fontsize=10.5, color=INK)
fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_joint_cotcontrol_k1.png", bbox_inches="tight"); plt.close(fig)

# Fig 3: CoTControl per-mode binary on singles, grouped bars
fig, ax = plt.subplots(figsize=(11, 4.2))
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = [100 * (per_bin(rows(l, "cotcontrol_multi", 1, mode=m), m)[0] or 0) for m in modes_cc]
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(modes_cc))], ys, width=w, color=C[arm(l)], edgecolor=SURF, alpha=1 if "final" in l or l == "base" else 0.55, label=l)
ax.set_xticks(range(len(modes_cc))); ax.set_xticklabels([m.replace("_", "\n") for m in modes_cc], fontsize=8.5); ax.set_ylabel("binary compliance, %"); style(ax)
ax.set_title("Qwen3-8B, CoTControl single-mode prompts: binary compliance per mode (lighter = step-60)", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=6, loc="upper center", bbox_to_anchor=(0.5, -0.22)); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_cotcontrol_modes.png", bbox_inches="tight"); plt.close(fig)

# Fig 4: CoTControl continuous macro, all modes vs excluding uppercase
fig, axes = plt.subplots(1, 2, figsize=(10, 3.8), sharey=True)
for ax, ex, ttl in zip(axes, (None, "uppercase_thinking"), ("all ten modes", "excluding uppercase_thinking")):
    ys = [cont_macro(l, exclude=ex) for l in LABS]
    ax.bar(range(len(LABS)), ys, color=[C[arm(l)] for l in LABS], width=0.62, edgecolor=SURF)
    for i, y in enumerate(ys): ax.text(i, y + 0.01, f"{y:.2f}", ha="center", fontsize=9, color=INK2)
    ax.set_xticks(range(len(LABS))); ax.set_xticklabels(LABS, fontsize=8.5); style(ax); ax.set_title(ttl, loc="left", fontsize=10, color=INK)
axes[0].set_ylabel("continuous compliance, macro over modes"); axes[0].set_ylim(0, 0.7)
fig.suptitle("Qwen3-8B, CoTControl single-mode prompts: continuous (graded) compliance", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_cotcontrol_continuous.png", bbox_inches="tight"); plt.close(fig)

# Fig 5: step-60 vs step-final on k=1, both suites, S1 and T3 (dumbbells)
fig, axes = plt.subplots(1, 2, figsize=(10, 3.2), sharey=True)
for ax, suite, ttl in zip(axes, ("reasonif_multi", "cotcontrol_multi"), ("ReasonIF k=1 (in-domain)", "CoTControl k=1 (transfer)")):
    for i, a in enumerate(("S1", "T3")):
        b = 100 * joint(rows("base", suite, 1))[0]; y60 = 100 * joint(rows(f"{a}-60", suite, 1))[0]; yf = 100 * joint(rows(f"{a}-final", suite, 1))[0]
        ax.plot([y60, yf], [i, i], color=GRID, lw=3, zorder=1); ax.plot([y60], [i], "o", color="#c3c2b7", ms=9, markeredgecolor=SURF, zorder=2); ax.plot([yf], [i], "o", color=C[a], ms=9, markeredgecolor=SURF, zorder=3)
        ax.axvline(b, color=MUTED, lw=1, ls=":")
    ax.set_yticks([0, 1]); ax.set_yticklabels(["S1", "T3"]); ax.set_xlabel("joint compliance, %"); ax.set_title(ttl, loc="left", fontsize=10, color=INK); ax.xaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
axes[0].set_ylim(-0.6, 1.6)
fig.legend(handles=[plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#c3c2b7", markeredgecolor=SURF, label="step-60 (240 examples)"), plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#2a78d6", markeredgecolor=SURF, label="step-final (~915; colour = arm)"), plt.Line2D([0], [0], ls=":", color=MUTED, label="base")], frameon=False, loc="lower center", bbox_to_anchor=(0.5, -0.06), ncol=3, fontsize=9)
fig.suptitle("Qwen3-8B: step-60 vs step-final on single-constraint prompts", x=0.01, ha="left", fontsize=10.5, color=INK); fig.tight_layout(rect=(0, 0.05, 1, 0.94)); fig.savefig(REPO / "figures/q3_8b_step60_vs_final.png", bbox_inches="tight"); plt.close(fig)

# Fig 6: cross-model comparison, base / S1 / T3 / T3 step-60 / Q5, ReasonIF k=1/k=3 and CoTControl k=1 (binary + continuous macro)
S35 = {l: json.load(open(REPO / f"results/multi_eval/{l}/summary.json")) for l in ("base", "S1-step-final", "T3-step-final", "T3-step-60")}
def s35(l, key): return S35[l].get(key)
def s35_cont(l):
    c = S35[l]["conditions"]; vals = [v["per_continuous"][k] for m, v in c.items() if v["suite"] == "cotcontrol_multi" and v["level"] == 1 for k in v["per_continuous"] if v["per_continuous"][k] is not None]
    return sum(vals) / len(vals)
ARMS6 = ["base", "S1", "T3", "T3-60", "Q5"]
L35 = {"base": "base", "S1": "S1-step-final", "T3": "T3-step-final", "T3-60": "T3-step-60", "Q5": None}
L38 = {"base": "base", "S1": "S1-final", "T3": "T3-final", "T3-60": "T3-60", "Q5": "Q5-final"}
def j38(l, suite, lvl): p, n = joint(rows(l, suite, lvl)); return None if p is None else 100 * p
panels = [("ReasonIF k=1, joint %", lambda l: 100 * s35(l, "reasonif_multi/k1/joint_macro"), lambda l: j38(l, "reasonif_multi", 1)),
          ("ReasonIF k=3, joint %", lambda l: 100 * s35(l, "reasonif_multi/k3/joint_macro"), lambda l: j38(l, "reasonif_multi", 3)),
          ("CoTControl k=1, joint %", lambda l: 100 * s35(l, "cotcontrol_multi/k1/joint_macro"), lambda l: j38(l, "cotcontrol_multi", 1)),
          ("CoTControl k=1, continuous macro", s35_cont, lambda l: cont_macro(l))]
fig, axes = plt.subplots(1, 4, figsize=(14, 3.8))
for ax, (ttl, f35, f38) in zip(axes, panels):
    x = range(len(ARMS6))
    v35 = [f35(L35[a]) if L35[a] else None for a in ARMS6]; v38 = [f38(L38[a]) for a in ARMS6]
    for i, a in enumerate(ARMS6):
        col = C[arm(a)]
        if v35[i] is not None: ax.bar(i - 0.19, v35[i], width=0.36, color=col, alpha=0.45, edgecolor=SURF); ax.text(i - 0.19, v35[i], f"{v35[i]:.0f}" if "joint" in ttl else f"{v35[i]:.2f}", ha="center", va="bottom", fontsize=8, color=MUTED)
        else: ax.text(i - 0.19, 0, "n/a", ha="center", va="bottom", fontsize=7.5, color=MUTED)
        if v38[i] is not None: ax.bar(i + 0.19, v38[i], width=0.36, color=col, edgecolor=SURF); ax.text(i + 0.19, v38[i], f"{v38[i]:.0f}" if "joint" in ttl else f"{v38[i]:.2f}", ha="center", va="bottom", fontsize=8, color=INK2)
        else: ax.text(i + 0.19, 0, "n/a", ha="center", va="bottom", fontsize=7.5, color=MUTED)
    ax.set_xticks(list(x)); ax.set_xticklabels(ARMS6, fontsize=8.5); ax.set_title(ttl, loc="left", fontsize=10, color=INK); style(ax)
fig.suptitle("Same constraint set, same recipe, two models: Qwen3.5-9B (faded, left bar) vs Qwen3-8B (solid, right bar); step-final unless marked -60\nQwen3.5 has no Q5 arm", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.legend(handles=[plt.Rectangle((0, 0), 1, 1, color="#104281", alpha=0.45, label="Qwen3.5-9B"), plt.Rectangle((0, 0), 1, 1, color="#104281", label="Qwen3-8B")], frameon=False, loc="lower center", bbox_to_anchor=(0.5, -0.04), ncol=2, fontsize=9)
fig.tight_layout(rect=(0, 0.04, 1, 0.9)); fig.savefig(REPO / "figures/q3_8b_vs_qwen35.png", bbox_inches="tight"); plt.close(fig)

# ---------------------------------------------------------------- additional figures
LANGN = {"en": "English", "es": "Spanish", "fr": "French", "ru": "Russian", "pl": "Polish", "zh": "Chinese", "hi": "Hindi", "ar": "Arabic"}
modes_rif = sorted({r["constraints"][0] for r in rows("base", "reasonif_multi", 1)})

# Fig 7: ReasonIF per-constraint singles, grouped bars, all six checkpoints
fig, ax = plt.subplots(figsize=(10, 4))
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = [100 * (per_bin(rows(l, "reasonif_multi", 1, mode=m), m)[0] or 0) for m in modes_rif]
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(modes_rif))], ys, width=w, color=C[arm(l)], edgecolor=SURF, alpha=1 if "final" in l or l == "base" else 0.55, label=l)
ax.set_xticks(range(len(modes_rif))); ax.set_xticklabels([m.replace("_", "\n") for m in modes_rif]); ax.set_ylabel("binary compliance, %"); style(ax); ax.set_ylim(0, 100)
ax.set_title("Qwen3-8B, ReasonIF single-constraint prompts: binary compliance per constraint (lighter = step-60)", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=6, loc="upper center", bbox_to_anchor=(0.5, -0.16)); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_reasonif_constraints.png", bbox_inches="tight"); plt.close(fig)

# Fig 8: per-constraint by number of rules, small multiples (ReasonIF, step-final arms)
fig, axes = plt.subplots(2, 3, figsize=(10.5, 5.6), sharex=True, sharey=True)
for ax, m in zip(axes.flat, modes_rif):
    for l in FINAL:
        pts = []
        for lvl in (1, 3, 5):
            v = [r["per_binary"][m] for r in rows(l, "reasonif_multi", lvl) if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]
            if v: pts.append((lvl, 100 * sum(v) / len(v)))
        ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=6, lw=2, color=C[arm(l)], markeredgecolor=SURF, label=l)
    ax.set_title(m, loc="left", fontsize=10, color=INK); style(ax); ax.set_xticks([1, 3, 5]); ax.set_ylim(0, 105)
axes[0][2].legend(frameon=False, fontsize=8, loc="upper left"); 
for ax in axes[1]: ax.set_xlabel("rules in the prompt")
for ax in axes[:, 0]: ax.set_ylabel("this constraint satisfied, %")
fig.suptitle("Qwen3-8B: per-constraint compliance rises with the number of rules in the prompt, for every trained arm", x=0.01, ha="left", fontsize=11, color=INK)
fig.tight_layout(rect=(0, 0, 1, 0.95)); fig.savefig(REPO / "figures/q3_8b_per_constraint_by_k.png", bbox_inches="tight"); plt.close(fig)

# Fig 9: per-mode compliance inside CoTControl combinations (k=3 and k=6), step-final arms
fig, axes = plt.subplots(1, 2, figsize=(14, 4.2), sharey=True)
for ax, lvl in zip(axes, (3, 6)):
    ms = [m for m in modes_cc if any(m in r["per_binary"] for r in rows("base", "cotcontrol_multi", lvl))]
    w = 0.8 / len(FINAL)
    for j, l in enumerate(FINAL):
        per = defaultdict(list)
        for r in rows(l, "cotcontrol_multi", lvl):
            if r["think_status"] != "ok": continue
            for m, b in r["per_binary"].items():
                if b is not None: per[m].append(b)
        ys = [100 * sum(per[m]) / len(per[m]) if per[m] else 0 for m in ms]
        ax.bar([i + (j - (len(FINAL) - 1) / 2) * w for i in range(len(ms))], ys, width=w, color=C[arm(l)], edgecolor=SURF, label=l)
    ax.set_xticks(range(len(ms))); ax.set_xticklabels([m.replace("_", "\n") for m in ms], fontsize=7.5); style(ax); ax.set_title(f"inside {lvl}-mode prompts (joint = 0 % for all)", loc="left", fontsize=10, color=INK)
axes[0].set_ylabel("this mode satisfied, % of rollouts asking for it"); axes[0].legend(frameon=False, fontsize=8.5, loc="upper left")
fig.suptitle("Qwen3-8B, CoTControl combinations: the transferred modes are applied inside multi-mode prompts too; the others never are", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.tight_layout(rect=(0, 0, 1, 0.94)); fig.savefig(REPO / "figures/q3_8b_cotcontrol_inside_combos.png", bbox_inches="tight"); plt.close(fig)

# Fig 10: CoTControl continuous per mode, grouped bars
fig, ax = plt.subplots(figsize=(11, 4))
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = [per_cont(rows(l, "cotcontrol_multi", 1, mode=m), m)[0] or 0 for m in modes_cc]
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(modes_cc))], ys, width=w, color=C[arm(l)], edgecolor=SURF, alpha=1 if "final" in l or l == "base" else 0.55, label=l)
ax.set_xticks(range(len(modes_cc))); ax.set_xticklabels([m.replace("_", "\n") for m in modes_cc], fontsize=8.5); ax.set_ylabel("continuous compliance (0–1)"); style(ax); ax.set_ylim(0, 1.05)
ax.set_title("Qwen3-8B, CoTControl single-mode prompts: continuous compliance per mode (ignore_question has no continuous score; lighter = step-60)", loc="left", fontsize=10, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=6, loc="upper center", bbox_to_anchor=(0.5, -0.22)); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_cotcontrol_continuous_modes.png", bbox_inches="tight"); plt.close(fig)

# Fig 11: ReasonIF condition heatmap (all 24 conditions x step-final checkpoints), † held-out
conds = []
for lvl in (1, 3, 5):
    for tag in sorted({r["mode"] for r in rows("base", "reasonif_multi", lvl)}):
        rs = rows("base", "reasonif_multi", lvl); held = any(r["held_out"] for r in rs if r["mode"] == tag)
        conds.append((tag, lvl, held))
import numpy as np
M = np.full((len(conds), len(FINAL)), np.nan)
for i, (tag, lvl, held) in enumerate(conds):
    for j, l in enumerate(FINAL):
        p, n = joint([r for r in rows(l, "reasonif_multi", lvl) if r["mode"] == tag]); M[i, j] = 100 * p if p is not None else np.nan
fig, ax = plt.subplots(figsize=(9.5, 0.32 * len(conds) + 1.2))
im = ax.imshow(M, cmap="Blues", vmin=0, vmax=100, aspect=0.55)
for i in range(len(conds)):
    for j in range(len(FINAL)):
        v = M[i, j]; ax.text(j, i, "—" if np.isnan(v) else f"{v:.0f}", ha="center", va="center", fontsize=8.5, color="white" if v > 55 else INK2)
ax.set_xticks(range(len(FINAL))); ax.set_xticklabels(FINAL, fontsize=9); ax.set_yticks(range(len(conds)))
ax.set_yticklabels([tag.split(":", 1)[1].replace("+", " + ") + (" †" if held else "") for tag, lvl, held in conds], fontsize=8); ax.tick_params(length=0)
for sp in ax.spines.values(): sp.set_visible(False)
ax.set_title("Qwen3-8B, ReasonIF: joint compliance per condition, step-final († = held out of training)", loc="left", fontsize=10, color=INK)
fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_condition_heatmap.png", bbox_inches="tight"); plt.close(fig)

# Fig 12: accuracy and truncation per checkpoint, both suites
fig, axes = plt.subplots(1, 2, figsize=(10, 3.6))
for ax, (ttl, f) in zip(axes, (("accuracy on k=1 prompts, %", lambda l, suite: 100 * acc(rows(l, suite, 1))), ("truncated at 32k, % of all rollouts", lambda l, suite: 100 * sum(r["truncated"] for r in rows(l, suite)) / len(rows(l, suite))))):
    for j, (suite, name, col) in enumerate((("reasonif_multi", "ReasonIF-side", "#2a78d6"), ("cotcontrol_multi", "CoTControl-side", "#eb6834"))):
        ys = [f(l, suite) for l in LABS]
        ax.bar([i + (j - 0.5) * 0.38 for i in range(len(LABS))], ys, width=0.36, color=col, edgecolor=SURF, label=name)
        for i, y in enumerate(ys): ax.text(i + (j - 0.5) * 0.38, y + 0.5, f"{y:.0f}", ha="center", fontsize=8, color=INK2)
    ax.set_xticks(range(len(LABS))); ax.set_xticklabels(LABS, fontsize=8.5); ax.set_title(ttl, loc="left", fontsize=10, color=INK); style(ax)
axes[0].set_ylim(0, 65); axes[0].legend(frameon=False, fontsize=8.5, loc="lower left"); fig.suptitle("Qwen3-8B: side effects by checkpoint", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.tight_layout(rect=(0, 0, 1, 0.94)); fig.savefig(REPO / "figures/q3_8b_accuracy_truncation.png", bbox_inches="tight"); plt.close(fig)

# Fig 13: reasoning_language by requested language (2-3 prompts per language per checkpoint)
langs = ["en", "es", "fr", "ru", "pl", "zh", "hi", "ar"]
LANG_OF = {l: {(r["sample_id"], r["mode"]): r["meta"].get("language") for r in (json.loads(x) for x in open(REPO / f"results/qwen3_8b/eval/{l}/rollouts.jsonl")) if r["meta"]["suite"] == "reasonif_multi"} for l in LABS}
fig, ax = plt.subplots(figsize=(10, 3.8))
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = []
    for lg in langs:
        rs = [r for r in rows(l, "reasonif_multi", 1, mode="reasoning_language") if r["think_status"] == "ok" and LANG_OF[l].get((r["sample_id"], r["mode"])) == lg]
        ys.append(100 * sum(r["per_binary"]["reasoning_language"] for r in rs) / len(rs) if rs else 0)
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(langs))], ys, width=w, color=C[arm(l)], edgecolor=SURF, alpha=1 if "final" in l or l == "base" else 0.55, label=l)
ax.axvline(4.5, color=MUTED, lw=1); ax.text(4.6, 106, "never trained on →", fontsize=8.5, color=MUTED)
ax.set_xticks(range(len(langs))); ax.set_xticklabels([LANGN[x] for x in langs]); ax.set_ylabel("reasoning in the requested language, %"); style(ax); ax.set_ylim(0, 114)
ax.set_title("Qwen3-8B, reasoning_language single prompts by requested language (2–3 prompts per language per checkpoint — indicative only)", loc="left", fontsize=10, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=6, loc="upper center", bbox_to_anchor=(0.5, -0.12)); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_language_breakdown.png", bbox_inches="tight"); plt.close(fig)

P("\n## Figures\n")
for f, cap in (("q3_8b_joint_reasonif", "ReasonIF joint by level"), ("q3_8b_joint_cotcontrol_k1", "CoTControl k=1 joint"), ("q3_8b_cotcontrol_modes", "CoTControl per-mode singles"),
               ("q3_8b_cotcontrol_continuous", "CoTControl continuous macro"), ("q3_8b_step60_vs_final", "step-60 vs step-final"), ("q3_8b_vs_qwen35", "Qwen3.5-9B vs Qwen3-8B"),
               ("q3_8b_reasonif_constraints", "ReasonIF per-constraint singles"), ("q3_8b_per_constraint_by_k", "per-constraint by number of rules"), ("q3_8b_cotcontrol_inside_combos", "CoTControl modes inside combinations"),
               ("q3_8b_cotcontrol_continuous_modes", "CoTControl continuous per mode"), ("q3_8b_condition_heatmap", "ReasonIF condition heatmap"), ("q3_8b_accuracy_truncation", "accuracy and truncation"), ("q3_8b_language_breakdown", "reasoning_language by language")):
    P(f"![{cap}](figures/{f}.png)\n")
(REPO / "QWEN3_8B_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote QWEN3_8B_RESULTS.md and 13 figures")
