#!/usr/bin/env python3
"""Tables and figures for the unlearning experiment (UNLEARNING_PLAN.md).

Reads results/unlearn/eval/<label>/graded.jsonl for whichever of Q5, base, S1-ifb, T3-60-ifb, U-15, U-final, C-15,
C-final exist. Writes UNLEARNING_RESULTS.md and figures/unlearn_*.png.
"""
from __future__ import annotations
import json, math, statistics as st
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[1]; EV = REPO / "results/unlearn/eval"
SURF, INK, INK2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"
C = {"base": "#c3c2b7", "S1-ifb": "#86b6ef", "T3-60-ifb": "#104281", "Q5": "#eb6834", "U-15": "#f2a37a", "U-final": "#b3261e", "C-15": "#9fd3a0", "C-final": "#1e7d3a"}
NAME = {"S1-ifb": "S1", "T3-60-ifb": "T3-60"}
plt.rcParams.update({"figure.facecolor": SURF, "axes.facecolor": SURF, "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED,
                     "font.size": 9.5, "axes.spines.top": False, "axes.spines.right": False, "savefig.dpi": 150, "savefig.facecolor": SURF})
UNLEARN_MODES = ["uppercase_thinking", "alternating_case", "word_suppression", "multiple_word_suppression", "repeat_sentences", "end_of_sentence", "meow_between_words", "ignore_question"]
HELD = ["json_format", "lowercase_thinking"]
RIF = ["reasoning_language", "number_words", "capital", "end_checker", "no_comma", "end_of_sentence"]
IFB = ["stop_words", "repeats", "conjunctions", "first_word_sent", "no_consecutive_initial", "newline_words", "square_brackets", "emoji_end", "sentence_type_ratio", "start_end_same"]

LABS = [l for l in ("base", "S1-ifb", "T3-60-ifb", "Q5", "U-15", "U-final", "C-15", "C-final") if (EV / l / "graded.jsonl").exists()]
G = {l: [json.loads(x) for x in open(EV / l / "graded.jsonl")] for l in LABS}
def nm(l): return NAME.get(l, l)
def rows(l, suite, mode=None, template=None):
    return [r for r in G[l] if r["suite"] == suite and (mode is None or r["constraints"][0] == mode) and (template is None or r["mode"].endswith(":" + template))]
def pb(rs, m):
    v = [r["per_binary"][m] for r in rs if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def pc(rs, m):
    v = [r["per_continuous"][m] for r in rs if r["think_status"] == "ok" and r["per_continuous"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def ci80(p, n): return 1.2816 * math.sqrt(p * (1 - p) / n) if n and p is not None else 0
def acc(rs): v = [r["correct"] for r in rs if r["correct"] is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def readouts(l):
    """The four readouts as (binary, continuous, n) macro over modes/constraints."""
    out = {}
    def macro(items):
        bs, cs, n = [], [], 0
        for suite, m, tpl in items:
            rs = rows(l, suite, m, tpl); b, nb = pb(rs, m); c, nc = pc(rs, m)
            if b is not None: bs.append(b); n += nb
            if c is not None: cs.append(c)
        return (sum(bs) / len(bs) if bs else None, sum(cs) / len(cs) if cs else None, n)
    out["trained-away CoTControl (8)"] = macro([("cotcontrol_multi", m, None) for m in UNLEARN_MODES])
    out["held-out CoTControl (json, lowercase)"] = macro([("cotcontrol_multi", m, None) for m in HELD])
    out["never-seen (10, both templates)"] = macro([("ifbench", m, t) for m in IFB for t in ("rif", "cc")])
    out["never-seen: stop_words"] = macro([("ifbench", "stop_words", t) for t in ("rif", "cc")])
    out["backward ReasonIF (6)"] = macro([("reasonif_multi", m, None) for m in RIF])
    return out

md = ["# Unlearning controllability: results\n", f"*Generated by `scripts/report_unlearn.py` from {', '.join(nm(l) for l in LABS)}. Binary = constraint satisfied (% of rollouts with a closed think block); continuous in [0,1]. Per-mode n = 20 (ReasonIF, never-seen per template) or 40 (CoTControl).*\n"]
P = md.append
KEYS = list(readouts(LABS[0]).keys())
P("\n## The four readouts (binary %, macro over constraints)\n")
P("| readout | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|" + "---:|" * len(LABS))
R = {l: readouts(l) for l in LABS}
for k in KEYS:
    P(f"| {k} | " + " | ".join("—" if R[l][k][0] is None else f"{100*R[l][k][0]:.0f}" for l in LABS) + " |")
P("\nContinuous:\n")
P("| readout | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for k in KEYS:
    P(f"| {k} | " + " | ".join("—" if R[l][k][1] is None else f"{R[l][k][1]:.2f}" for l in LABS) + " |")

P("\n## CoTControl single-mode prompts (binary % / continuous)\n")
P("| mode | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for m in HELD + UNLEARN_MODES:
    cells = []
    for l in LABS:
        b, nb = pb(rows(l, "cotcontrol_multi", m), m); c, nc = pc(rows(l, "cotcontrol_multi", m), m)
        cells.append("—" if b is None else f"{100*b:.0f}" + ("" if c is None else f" / {c:.2f}"))
    P(f"| {m}{' (held out)' if m in HELD else ''} | " + " | ".join(cells) + " |")
P("\n## Backward: ReasonIF single constraints (binary % / continuous)\n")
P("| constraint | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for m in RIF:
    cells = []
    for l in LABS:
        b, nb = pb(rows(l, "reasonif_multi", m), m); c, nc = pc(rows(l, "reasonif_multi", m), m)
        cells.append("—" if b is None else f"{100*b:.0f}" + ("" if c is None else f" / {c:.2f}"))
    P(f"| {m} | " + " | ".join(cells) + " |")
P("\n## Never-seen constraints (binary % / continuous), by template\n")
P("| constraint | template | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|---|" + "---:|" * len(LABS))
for m in IFB:
    for t in ("rif", "cc"):
        cells = []
        for l in LABS:
            b, nb = pb(rows(l, "ifbench", m, t), m); c, nc = pc(rows(l, "ifbench", m, t), m)
            cells.append("—" if b is None else f"{100*b:.0f}" + ("" if c is None else f" / {c:.2f}"))
        P(f"| {m} | {t} | " + " | ".join(cells) + " |")
P("\n## Accuracy (%, answered prompts) and trace status\n")
P("| | " + " | ".join(nm(l) for l in LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for suite, name in (("reasonif_multi", "ReasonIF k=1"), ("cotcontrol_multi", "CoTControl k=1"), ("ifbench", "never-seen")):
    P(f"| accuracy, {name} | " + " | ".join("—" if acc(rows(l, suite))[0] is None else f"{100*acc(rows(l, suite))[0]:.0f}" for l in LABS) + " |")
P("| empty / unclosed think blocks | " + " | ".join(str(sum(r['think_status'] != 'ok' for r in G[l])) for l in LABS) + " |")
P("| median completion tokens, CoTControl k=1 | " + " | ".join(str(int(st.median(r['completion_tokens'] for r in rows(l, 'cotcontrol_multi')))) if rows(l, 'cotcontrol_multi') else "—" for l in LABS) + " |")

# ---------------------------------------------------------------- figures
def style(ax): ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
ARMS = [l for l in ("Q5", "U-15", "U-final", "C-15", "C-final") if l in LABS]
# Fig 1: the four readouts, Q5 vs U vs C
fig, axes = plt.subplots(1, len(KEYS), figsize=(3.1 * len(KEYS), 3.8), sharey=True)
for ax, k in zip(axes, KEYS):
    ys = [100 * (R[l][k][0] or 0) for l in ARMS]
    ax.bar(range(len(ARMS)), ys, color=[C[l] for l in ARMS], width=0.65, edgecolor=SURF)
    for i, y in enumerate(ys): ax.text(i, y + 1, f"{y:.0f}", ha="center", fontsize=8.5, color=INK2)
    ax.set_xticks(range(len(ARMS))); ax.set_xticklabels(ARMS, fontsize=8, rotation=20); ax.set_title(k, loc="left", fontsize=9.5, color=INK); style(ax)
axes[0].set_ylabel("binary compliance, %"); axes[0].set_ylim(0, 100)
fig.suptitle("Unlearning eight CoTControl modes on Q5: U (instruction present, trace ignores it) vs C (same traces, no instruction)", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.tight_layout(rect=(0, 0, 1, 0.93)); fig.savefig(REPO / "figures/unlearn_readouts.png", bbox_inches="tight"); plt.close(fig)
# Fig 2: CoTControl per mode
fig, ax = plt.subplots(figsize=(11, 4)); modes = HELD + UNLEARN_MODES; w = 0.8 / len(ARMS)
for j, l in enumerate(ARMS):
    ys = [100 * (pb(rows(l, "cotcontrol_multi", m), m)[0] or 0) for m in modes]
    ax.bar([i + (j - (len(ARMS) - 1) / 2) * w for i in range(len(modes))], ys, width=w, color=C[l], edgecolor=SURF, label=l)
ax.axvline(1.5, color=MUTED, lw=1, ls=":"); ax.text(0.5, 92, "held out of unlearning", ha="center", fontsize=8.5, color=MUTED); ax.text(5.5, 92, "trained to be ignored", ha="center", fontsize=8.5, color=MUTED)
ax.set_xticks(range(len(modes))); ax.set_xticklabels([m.replace("_", "\n") for m in modes], fontsize=8); ax.set_ylabel("binary compliance, %"); style(ax); ax.set_ylim(0, 100)
ax.set_title("CoTControl single-mode prompts after unlearning", loc="left", fontsize=10.5, color=INK); ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.2))
fig.tight_layout(); fig.savefig(REPO / "figures/unlearn_cotcontrol_modes.png", bbox_inches="tight"); plt.close(fig)
# Fig 3: backward ReasonIF per constraint
fig, ax = plt.subplots(figsize=(9, 3.8)); w = 0.8 / len(ARMS)
for j, l in enumerate(ARMS):
    ys = [100 * (pb(rows(l, "reasonif_multi", m), m)[0] or 0) for m in RIF]
    ax.bar([i + (j - (len(ARMS) - 1) / 2) * w for i in range(len(RIF))], ys, width=w, color=C[l], edgecolor=SURF, label=l)
ax.set_xticks(range(len(RIF))); ax.set_xticklabels([m.replace("_", "\n") for m in RIF], fontsize=8.5); ax.set_ylabel("binary compliance, %"); style(ax); ax.set_ylim(0, 105)
ax.set_title("Backward: the six phase-1 ReasonIF constraints (never in the unlearning data, other template)", loc="left", fontsize=10.5, color=INK); ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.2))
fig.tight_layout(); fig.savefig(REPO / "figures/unlearn_backward_reasonif.png", bbox_inches="tight"); plt.close(fig)
# Fig 4: never-seen constraints, all checkpoints, pooled over templates, only the constraints anyone is above floor on
fig, ax = plt.subplots(figsize=(10, 3.8)); ifb_show = [m for m in IFB if any((pb(rows(l, "ifbench", m), m)[0] or 0) >= 0.05 or (pc(rows(l, "ifbench", m), m)[0] or 0) >= 0.1 for l in LABS)]
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = [100 * (pb(rows(l, "ifbench", m), m)[0] or 0) for m in ifb_show]
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(ifb_show))], ys, width=w, color=C[l], edgecolor=SURF, label=nm(l))
ax.set_xticks(range(len(ifb_show))); ax.set_xticklabels([m.replace("_", "\n") for m in ifb_show], fontsize=8.5); ax.set_ylabel("binary compliance, % (both templates pooled)"); style(ax)
ax.set_title(f"Never-seen constraints with any non-floor score ({len(IFB) - len(ifb_show)} of {len(IFB)} at zero for every checkpoint are omitted)", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=len(LABS), loc="upper center", bbox_to_anchor=(0.5, -0.2)); fig.tight_layout(); fig.savefig(REPO / "figures/unlearn_never_seen.png", bbox_inches="tight"); plt.close(fig)
# Fig 5: dose curves (0 = Q5, 60 = step-15, ~667 = final) for the readouts, U vs C
dose = {"Q5": 0, "U-15": 60, "C-15": 60, "U-final": 667, "C-final": 667}
fig, axes = plt.subplots(1, len(KEYS), figsize=(3.1 * len(KEYS), 3.4), sharey=True)
for ax, k in zip(axes, KEYS):
    for arm, col in (("U", C["U-final"]), ("C", C["C-final"])):
        pts = sorted((dose[l], 100 * (R[l][k][0] or 0)) for l in ["Q5"] + [x for x in ARMS if x.startswith(arm)])
        xs = [{0: 0, 60: 1, 667: 2}[p[0]] for p in pts]; ax.plot(xs, [p[1] for p in pts], marker="o", ms=6, lw=2, color=col, markeredgecolor=SURF, label=arm)
    ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["Q5\n(0 ex.)", "60 ex.", "667 ex."], fontsize=8); ax.set_title(k, loc="left", fontsize=9, color=INK); style(ax)
axes[0].set_ylabel("binary compliance, %"); axes[0].set_ylim(0, 100); axes[0].legend(frameon=False, fontsize=8.5)
fig.suptitle("Dose: unlearning examples seen (U) vs the matched control (C)", x=0.01, ha="left", fontsize=10.5, color=INK); fig.tight_layout(rect=(0, 0, 1, 0.92)); fig.savefig(REPO / "figures/unlearn_dose.png", bbox_inches="tight"); plt.close(fig)
# Fig 6: accuracy
fig, ax = plt.subplots(figsize=(8, 3.4)); suites = [("reasonif_multi", "ReasonIF k=1"), ("cotcontrol_multi", "CoTControl k=1"), ("ifbench", "never-seen")]; w = 0.8 / len(suites)
for j, (s, name) in enumerate(suites):
    ys = [100 * (acc(rows(l, s))[0] or 0) for l in LABS]
    ax.bar([i + (j - 1) * w for i in range(len(LABS))], ys, width=w, color=["#2a78d6", "#eb6834", "#1e7d3a"][j], edgecolor=SURF, label=name)
ax.set_xticks(range(len(LABS))); ax.set_xticklabels([nm(l) for l in LABS], fontsize=8.5); ax.set_ylabel("accuracy, % of answered"); style(ax); ax.set_ylim(0, 100)
ax.set_title("Accuracy by checkpoint and suite", loc="left", fontsize=10.5, color=INK); ax.legend(frameon=False, fontsize=8.5, ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.18))
fig.tight_layout(); fig.savefig(REPO / "figures/unlearn_accuracy.png", bbox_inches="tight"); plt.close(fig)
P("\n## Figures\n")
for f in ("unlearn_readouts", "unlearn_cotcontrol_modes", "unlearn_backward_reasonif", "unlearn_never_seen", "unlearn_dose", "unlearn_accuracy"): P(f"![{f}](figures/{f}.png)\n")
(REPO / "UNLEARNING_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote UNLEARNING_RESULTS.md and 6 figures for", [nm(l) for l in LABS])
