#!/usr/bin/env python3
"""Cross-arm report for the multi-constraint experiment. Reads results/multi_eval/<label>/summary.json and
graded.jsonl for every label present; writes MULTI_CONSTRAINT_RESULTS.md (tables) and figures/multi_*.png."""
from __future__ import annotations
import glob, json, random, statistics as st, sys
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
REPO = Path(__file__).resolve().parents[1]
SURF, INK, INK2, MUTED, GRID, BASE = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7"
ARMC = {"base": BASE, "S1": "#86b6ef", "P2": "#2a78d6", "T3": "#104281", "M": "#eb6834"}
plt.rcParams.update({"font.family": "sans-serif", "font.size": 10, "text.color": INK, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED, "axes.edgecolor": BASE, "axes.facecolor": SURF, "figure.facecolor": SURF, "savefig.facecolor": SURF, "axes.spines.top": False, "axes.spines.right": False})
labels = sorted(p.parent.name for p in (REPO / "results/multi_eval").glob("*/summary.json"))
S = {l: json.load(open(REPO / "results/multi_eval" / l / "summary.json")) for l in labels}
G = {l: [json.loads(x) for x in open(REPO / "results/multi_eval" / l / "graded.jsonl")] for l in labels}
def arm(l): return l.split("-")[0]
def step(l): return l.split("-", 1)[1] if "-" in l else ""
def mean(xs): xs = [x for x in xs if x is not None]; return st.mean(xs) if xs else None
def wald(p, n, z=1.2816): return (z * (p * (1 - p) / n) ** 0.5) if n and p is not None else None
def rate(l, suite, level, held=None, ok_only=True):
    gs = [g for g in G[l] if g["suite"] == suite and g["level"] == level and (held is None or g["held_out"] == held) and (g["think_status"] == "ok" or not ok_only)]
    v = [g["joint"] for g in gs if g["joint"] is not None]; return (mean(v), len(v))
md = ["# Multi-constraint SFT: results\n", f"*Generated by `scripts/report_multi.py` from {len(labels)} evaluated checkpoint(s): {', '.join(labels)}.*\n"]
P = md.append
for suite, name in (("reasonif_multi", "ReasonIF-side, all combinations (seen and held-out pooled)"), ("cotcontrol_multi", "CoTControl-side (transfer)")):
    P(f"\n## {name}: joint binary compliance (all constraints satisfied), % of gradeable rollouts\n")
    cols = ["singles", "pairs (seen)", "pairs (held-out)", "triples (seen)", "triples (held-out)"] if suite == "reasonif_multi" else ["singles", "pairs", "triples"]
    P("| checkpoint | " + " | ".join(cols) + " | accuracy | truncated |"); P("|---|" + "---:|" * (len(cols) + 2))
    for l in labels:
        cells = []
        if suite == "reasonif_multi":
            for lvl, held in ((1, None), (2, False), (2, True), (3, False), (3, True)):
                r, n = rate(l, suite, lvl, held); cells.append(f"{100*r:.1f} ± {100*wald(r,n):.1f} (n {n})" if r is not None else "—")
        else:
            for lvl in (1, 2, 3):
                r, n = rate(l, suite, lvl); cells.append(f"{100*r:.1f} ± {100*wald(r,n):.1f} (n {n})" if r is not None else "—")
        gs = [g for g in G[l] if g["suite"] == suite]; acc = mean([g["correct"] for g in gs]); tr = mean([g["truncated"] for g in gs])
        P(f"| {l} | " + " | ".join(cells) + f" | {100*acc:.0f} % | {100*tr:.0f} % |")
    P(f"\n![joint compliance by level]({'figures/multi_joint_' + suite + '.png'})\n")
    # per-condition table
    P(f"\n### Per condition (joint %, gradeable n)\n")
    conds = sorted({m for l in labels for m in S[l]["conditions"] if S[l]["conditions"][m]["suite"] == suite}, key=lambda m: (S[labels[0]]["conditions"].get(m, {}).get("level", 9), m))
    P("| condition | " + " | ".join(labels) + " |"); P("|---|" + "---:|" * len(labels))
    for m in conds:
        row = []
        for l in labels:
            c = S[l]["conditions"].get(m); row.append(f"{100*c['joint_binary']:.0f} ({c['gradeable']})" if c and c["joint_binary"] is not None else "—")
        P(f"| {m}{' †' if any(S[l]['conditions'].get(m,{}).get('held_out') for l in labels) else ''} | " + " | ".join(row) + " |")
    P("\n† held out of training in every arm.\n")
    # per-constraint binary across levels (does compliance per constraint drop as k grows?)
    P(f"\n### Per-constraint binary compliance by level (%, averaged over conditions containing the constraint)\n")
    cons = sorted({c for l in labels for m, cd in S[l]["conditions"].items() if cd["suite"] == suite for c in cd["per_binary"]})
    P("| checkpoint | constraint | k=1 | k=2 | k=3 |"); P("|---|---|---:|---:|---:|")
    for l in labels:
        for c in cons:
            vals = []
            for lvl in (1, 2, 3):
                xs = [cd["per_binary"][c] for cd in S[l]["conditions"].values() if cd["suite"] == suite and cd["level"] == lvl and c in cd["per_binary"] and cd["per_binary"][c] is not None]
                vals.append(f"{100*st.mean(xs):.0f}" if xs else "—")
            P(f"| {l} | {c} | " + " | ".join(vals) + " |")
    # figure: joint by level per arm (step-final preferred), lines per arm
    fig, ax = plt.subplots(figsize=(7.5, 4), dpi=150)
    for l in labels:
        pts = [(lvl, rate(l, suite, lvl)[0]) for lvl in (1, 2, 3)]; pts = [(x, 100 * y) for x, y in pts if y is not None]
        if pts: ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=ARMC.get(arm(l), INK2), ls="-" if "final" in l or l == "base" else "--", markeredgecolor=SURF, label=l)
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(["1 constraint", "2", "3"]); ax.set_ylabel("joint compliance, %", color=INK2); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
    ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.14)); ax.set_title(f"{name}: joint compliance vs number of constraints\nsolid = step-final (~915 examples), dashed = step-60 (240 examples); colour = arm", loc="left", fontsize=10.5, color=INK)
    ax.set_ylim(0, max(ax.get_ylim()[1], 1) * 1.05); fig.tight_layout(); fig.savefig(REPO / f"figures/multi_joint_{suite}.png", bbox_inches="tight"); plt.close(fig)
# three ReasonIF-side figures: seen-only, held-out-only, and T3 seen vs held-out
def lvl_fig(fname, title, xt, held_sel, only_labels=None, two_series=False):
    fig, ax = plt.subplots(figsize=(7.5, 4), dpi=150)
    for l in labels:
        if only_labels and l not in only_labels: continue
        series = [("seen", False, "-"), ("held-out", True, ":")] if two_series else [(None, held_sel, "-" if "final" in l or l == "base" else "--")]
        for name_, held, ls in series:
            pts = []
            for lvl in (1, 2, 3):
                if lvl == 1 and held is True: continue  # singles are all seen
                r = rate(l, "reasonif_multi", lvl, (None if lvl == 1 else held))[0]
                if r is not None: pts.append((lvl, 100 * r))
            lab = f"{l} ({name_})" if name_ else l
            col = ARMC.get(arm(l), INK2) if not two_series else ("#104281" if "final" in l else "#86b6ef")
            ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=col, ls=ls, markeredgecolor=SURF, label=lab)
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(xt); ax.set_ylabel("joint compliance, %", color=INK2); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
    ax.legend(frameon=False, fontsize=8.5, ncol=4 if two_series else 5, loc="upper center", bbox_to_anchor=(0.5, -0.2)); ax.set_ylim(0, max(ax.get_ylim()[1], 1) * 1.05)
    ax.set_title(title, loc="left", fontsize=10.5, color=INK); fig.tight_layout(); fig.savefig(REPO / f"figures/{fname}", bbox_inches="tight"); plt.close(fig)
lvl_fig("multi_joint_reasonif_seen.png", "ReasonIF-side: combinations that appeared in training (10 of 14 pairs, 12 of 16 triples)\nsolid = step-final, dashed = step-60; colour = arm", ["1 constraint", "2 (seen pairs)", "3 (seen triples)"], False)
lvl_fig("multi_joint_reasonif_heldout.png", "ReasonIF-side: combinations never seen in training (4 pairs, 4 triples)\nsolid = step-final, dashed = step-60; colour = arm", ["1 constraint\n(reference, all seen)", "2 (held-out pairs)", "3 (held-out triples)"], True)
lvl_fig("multi_joint_reasonif_T3_seen_vs_heldout.png", "Triples arm (T3): seen vs held-out combinations\nsolid = seen, dotted = held-out; dark = step-final, light = step-60", ["1 constraint", "2", "3"], None, only_labels=["T3-step-60", "T3-step-final"], two_series=True)
for fn, cap in (("multi_joint_reasonif_seen.png", "seen combinations only"), ("multi_joint_reasonif_heldout.png", "held-out combinations only"), ("multi_joint_reasonif_T3_seen_vs_heldout.png", "T3: seen vs held-out")):
    k = "\n## CoTControl-side (transfer): joint binary compliance (all constraints satisfied), % of gradeable rollouts\n"; md.insert(md.index(k) if k in md else len(md), f"\n![{cap}](figures/{fn})\n")
(REPO / "MULTI_CONSTRAINT_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote MULTI_CONSTRAINT_RESULTS.md and figures for", labels)

# ---------------------------------------------------------------- additional figures (2026-09-25)
import numpy as np
FINALS = [l for l in ["base", "S1-step-final", "P2-step-final", "M-step-final", "T3-step-final"] if l in S]
short = lambda l: l.replace("-step-final", "").replace("-step-60", " (60)")
CONS = ["reasoning_language", "number_words", "capital", "end_checker", "no_comma", "end_of_sentence"]
def per_con(l, c, lvl):
    xs = [cd["per_binary"][c] for cd in S[l]["conditions"].values() if cd["suite"] == "reasonif_multi" and cd["level"] == lvl and cd["per_binary"].get(c) is not None]
    return 100 * st.mean(xs) if xs else None
# A. per-constraint binary on singles, by arm (grouped bars)
fig, ax = plt.subplots(figsize=(10, 4), dpi=150); w = 0.16
for i, l in enumerate(FINALS):
    vals = [per_con(l, c, 1) or 0 for c in CONS]; ax.bar([j + (i - 2) * w for j in range(len(CONS))], vals, width=w, color=ARMC[arm(l)], label=short(l), zorder=3)
    for j, v in enumerate(vals): ax.text(j + (i - 2) * w, v + 1, f"{v:.0f}", ha="center", va="bottom", fontsize=7, color=INK2)
ax.set_xticks(range(len(CONS))); ax.set_xticklabels([c.replace("_", "\n") for c in CONS], fontsize=9, color=INK2); ax.set_ylim(0, 100); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.spines["left"].set_visible(False); ax.tick_params(length=0)
ax.set_ylabel("binary compliance on single constraints, %", color=INK2); ax.legend(frameon=False, fontsize=9, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.18))
ax.set_title("Each constraint on its own (single-constraint prompts), step-final checkpoints", loc="left", fontsize=11, color=INK); fig.tight_layout(); fig.savefig(REPO / "figures/multi_per_constraint_singles.png", bbox_inches="tight"); plt.close(fig)
# B. per-constraint binary vs number of rules in the prompt, small multiples per constraint, lines per arm
fig, axes = plt.subplots(2, 3, figsize=(10.5, 6), dpi=150, sharex=True, sharey=True)
for ax, c in zip(axes.flat, CONS):
    for l in FINALS:
        pts = [(k, per_con(l, c, k)) for k in (1, 2, 3)]; pts = [(x, y) for x, y in pts if y is not None]
        ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=6, lw=2, color=ARMC[arm(l)], markeredgecolor=SURF, label=short(l))
    ax.set_title(c, loc="left", fontsize=10, color=INK); ax.set_xticks([1, 2, 3]); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False); ax.set_ylim(0, 100)
for ax in axes[-1]: ax.set_xlabel("rules in the prompt", color=INK2)
for ax in axes[:, 0]: ax.set_ylabel("this constraint satisfied, %", color=INK2, fontsize=9)
axes[0][2].legend(frameon=False, fontsize=8, loc="upper left"); fig.suptitle("Per-constraint compliance rises with the number of rules for the multi-constraint arms and falls for S1", x=0.01, ha="left", fontsize=11, color=INK)
fig.tight_layout(rect=(0, 0, 1, 0.96)); fig.savefig(REPO / "figures/multi_per_constraint_by_k.png", bbox_inches="tight"); plt.close(fig)
# C. heatmap: conditions (ReasonIF side) x arms (step-final), joint %, held-out marked
conds = sorted([m for m, cd in S[FINALS[-1]]["conditions"].items() if cd["suite"] == "reasonif_multi"], key=lambda m: (S[FINALS[-1]]["conditions"][m]["level"], m))
M_ = np.array([[100 * (S[l]["conditions"].get(m, {}).get("joint_binary") or 0) for l in FINALS] for m in conds])
fig, ax = plt.subplots(figsize=(6.5, 0.28 * len(conds) + 1.2), dpi=150)
im = ax.imshow(M_, cmap=matplotlib.colors.LinearSegmentedColormap.from_list("b", ["#f2f6fc", "#2a78d6", "#0d366b"]), vmin=0, vmax=100, aspect="auto")
for i in range(len(conds)):
    for j in range(len(FINALS)): ax.text(j, i, f"{M_[i, j]:.0f}", ha="center", va="center", fontsize=7.5, color=SURF if M_[i, j] > 45 else INK)
held = {m for l in FINALS for m, cd in S[l]["conditions"].items() if cd.get("held_out")}
ax.set_yticks(range(len(conds))); ax.set_yticklabels([m.split(":", 1)[1].replace("+", " + ") + (" †" if m in held else "") for m in conds], fontsize=7.5, color=INK2)
ax.set_xticks(range(len(FINALS))); ax.set_xticklabels([short(l) for l in FINALS], fontsize=9, color=INK2); ax.tick_params(length=0)
ax.set_title("Joint compliance per condition, step-final († = held out of training)", loc="left", fontsize=10, color=INK); fig.tight_layout(); fig.savefig(REPO / "figures/multi_condition_heatmap.png", bbox_inches="tight"); plt.close(fig)
# D. step-60 vs step-final per arm and level (dumbbell)
fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.4), dpi=150, sharey=True)
arms = [a for a in ["S1", "P2", "M", "T3"] if f"{a}-step-60" in S and f"{a}-step-final" in S]; ys = list(range(len(arms)))[::-1]
for ax, lvl, lab in zip(axes, (1, 2, 3), ("singles", "pairs (all)", "triples (all)")):
    for y, a in zip(ys, arms):
        r60, rf = rate(f"{a}-step-60", "reasonif_multi", lvl)[0], rate(f"{a}-step-final", "reasonif_multi", lvl)[0]
        if r60 is None or rf is None: continue
        ax.plot([100 * r60, 100 * rf], [y, y], color=GRID, lw=2, zorder=2); ax.scatter(100 * r60, y, s=60, color="#c3c2b7", edgecolor=SURF, linewidth=2, zorder=4); ax.scatter(100 * rf, y, s=70, color=ARMC[a], edgecolor=SURF, linewidth=2, zorder=5)
    ax.set_yticks(ys); ax.set_yticklabels(arms, color=INK2); ax.set_xlim(0, 65); ax.xaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_color(BASE); ax.set_title(lab, loc="left", fontsize=10, color=INK); ax.set_xlabel("joint compliance, %", color=INK2)
fig.legend(handles=[plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#c3c2b7", markeredgecolor=SURF, label="step-60 (240 examples)"), plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#2a78d6", markeredgecolor=SURF, label="step-final (~915 examples; colour = arm)")], frameon=False, loc="upper left", bbox_to_anchor=(0.01, 0.97), ncol=2, fontsize=9)
fig.suptitle("More data helps the multi-constraint arms and not S1", x=0.01, ha="left", fontsize=11, color=INK); fig.tight_layout(rect=(0, 0, 1, 0.88)); fig.savefig(REPO / "figures/multi_step60_vs_final.png", bbox_inches="tight"); plt.close(fig)
# E. accuracy and truncation by arm and suite
fig, axes = plt.subplots(1, 2, figsize=(9, 3.4), dpi=150)
for ax, key, lab, ymax in ((axes[0], "correct", "accuracy, %", 100), (axes[1], "truncated", "truncated at 32k tokens, %", 20)):
    for i, suite in enumerate(("reasonif_multi", "cotcontrol_multi")):
        vals = [100 * (mean([g[key] for g in G[l] if g["suite"] == suite]) or 0) for l in FINALS]
        ax.bar([j + (i - 0.5) * 0.36 for j in range(len(FINALS))], vals, width=0.34, color=["#2a78d6", "#eb6834"][i], label=["ReasonIF-side", "CoTControl-side"][i], zorder=3)
        for j, v in enumerate(vals): ax.text(j + (i - 0.5) * 0.36, v + ymax * 0.01, f"{v:.0f}", ha="center", va="bottom", fontsize=8, color=INK2)
    ax.set_xticks(range(len(FINALS))); ax.set_xticklabels([short(l) for l in FINALS], color=INK2); ax.set_ylim(0, ymax); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.spines["left"].set_visible(False); ax.tick_params(length=0); ax.set_title(lab, loc="left", fontsize=10, color=INK)
axes[0].legend(frameon=False, fontsize=9, loc="lower left"); fig.suptitle("Side effects by arm (step-final)", x=0.01, ha="left", fontsize=11, color=INK); fig.tight_layout(rect=(0, 0, 1, 0.94)); fig.savefig(REPO / "figures/multi_accuracy_truncation.png", bbox_inches="tight"); plt.close(fig)
# F. reasoning_language single by language: trained languages vs never-trained (zh/hi/ar)
langs = ["en", "es", "fr", "ru", "pl", "zh", "hi", "ar"]
fig, ax = plt.subplots(figsize=(10, 3.8), dpi=150); w = 0.16
for i, l in enumerate(FINALS):
    R_ = {(r["sample_id"], r["mode"]): r for r in (json.loads(x) for x in open(REPO / "results/multi_eval" / l / "rollouts.jsonl"))}
    gl = defaultdict(list)
    for g in G[l]:
        if g["mode"] == "single:reasoning_language" and g["think_status"] == "ok":
            r = R_.get((g["sample_id"], g["mode"]));  gl[r["meta"]["language"] if r else "?"].append(g["joint"])
    vals = [100 * st.mean(gl[x]) if gl[x] else 0 for x in langs]
    ax.bar([j + (i - 2) * w for j in range(len(langs))], vals, width=w, color=ARMC[arm(l)], label=short(l), zorder=3)
ax.axvline(4.5, color=BASE, lw=1); ax.text(4.55, 95, "never trained on →", fontsize=8.5, color=MUTED, va="top")
ax.set_xticks(range(len(langs))); ax.set_xticklabels([LANGN.get(x, x) if (LANGN := {"en": "English", "es": "Spanish", "fr": "French", "ru": "Russian", "pl": "Polish", "zh": "Chinese", "hi": "Hindi", "ar": "Arabic"}) else x for x in langs], color=INK2); ax.set_ylim(0, 100); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.spines["left"].set_visible(False); ax.tick_params(length=0)
ax.set_ylabel("reasoning in the requested language, %", color=INK2); ax.legend(frameon=False, fontsize=9, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.12))
ax.set_title("reasoning_language single, by language (6–7 prompts per language per checkpoint — indicative only)", loc="left", fontsize=10, color=INK); fig.tight_layout(); fig.savefig(REPO / "figures/multi_language_breakdown.png", bbox_inches="tight"); plt.close(fig)
extra = ["\n## Additional figures\n", "![per-constraint singles](figures/multi_per_constraint_singles.png)\n", "![per-constraint by k](figures/multi_per_constraint_by_k.png)\n", "![condition heatmap](figures/multi_condition_heatmap.png)\n", "![step-60 vs final](figures/multi_step60_vs_final.png)\n", "![accuracy and truncation](figures/multi_accuracy_truncation.png)\n", "![language breakdown](figures/multi_language_breakdown.png)\n"]
with open(REPO / "MULTI_CONSTRAINT_RESULTS.md", "a", encoding="utf-8") as f: f.write("\n".join(extra))

# CoTControl-side excluding uppercase_thinking (the mode closest to the trained `capital` constraint):
# singles drop the mode; pairs/triples drop every combination containing it.
def rate_excl(l, level, mode="uppercase_thinking"):
    gs = [g for g in G[l] if g["suite"] == "cotcontrol_multi" and g["level"] == level and g["think_status"] == "ok" and mode not in g["constraints"]]
    v = [g["joint"] for g in gs if g["joint"] is not None]; return (mean(v), len(v))
fig, axes = plt.subplots(1, 2, figsize=(10, 4), dpi=150, sharey=True, gridspec_kw={"wspace": 0.12})
for ax, (ttl, fn) in zip(axes, (("all ten modes (as before)", lambda l, k: rate(l, "cotcontrol_multi", k)[0]), ("excluding uppercase_thinking", lambda l, k: rate_excl(l, k)[0]))):
    for l in labels:
        pts = [(lvl, fn(l, lvl)) for lvl in (1, 2, 3)]; pts = [(x, 100 * y) for x, y in pts if y is not None]
        if pts: ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=ARMC.get(arm(l), INK2), ls="-" if "final" in l or l == "base" else "--", markeredgecolor=SURF, label=l)
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(["1 constraint", "2", "3"]); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False); ax.set_title(ttl, loc="left", fontsize=10.5, color=INK)
axes[0].set_ylabel("joint compliance, %", color=INK2); axes[0].set_ylim(0, 5)
h, lb = axes[0].get_legend_handles_labels(); fig.legend(h, lb, frameon=False, fontsize=8.5, ncol=5, loc="lower center", bbox_to_anchor=(0.5, 0.0))
fig.suptitle("CoTControl-side (transfer): joint binary compliance with and without the uppercase mode\nsolid = step-final, dashed = step-60; pairs/triples on the right exclude every combination containing uppercase_thinking", x=0.01, y=0.98, ha="left", fontsize=10.5, color=INK)
fig.subplots_adjust(top=0.76, bottom=0.22, left=0.08, right=0.98, wspace=0.12); fig.savefig(REPO / "figures/multi_joint_cotcontrol_excl_uppercase.png", bbox_inches="tight"); plt.close(fig)
with open(REPO / "MULTI_CONSTRAINT_RESULTS.md", "a", encoding="utf-8") as f: f.write("\n![CoTControl excluding uppercase](figures/multi_joint_cotcontrol_excl_uppercase.png)\n")
print("wrote 7 additional figures")
