#!/usr/bin/env python3
"""Cross-arm report for the multi-constraint experiment. Reads results/multi_eval/<label>/summary.json and
graded.jsonl for every label present; writes MULTI_CONSTRAINT_RESULTS.md (tables) and figures/multi_*.png."""
from __future__ import annotations
import glob, json, random, statistics as st, sys
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
REPO = Path(__file__).resolve().parents[1]
SURF, INK, INK2, MUTED, GRID, BASE = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7"
ARMC = {"base": BASE, "S1": "#86b6ef", "P2": "#2a78d6", "T3": "#104281", "M": "#eb6834"}
plt.rcParams.update({"font.family": "sans-serif", "font.size": 10, "text.color": INK, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED, "axes.edgecolor": BASE, "axes.facecolor": SURF, "figure.facecolor": SURF, "savefig.facecolor": SURF, "axes.spines.top": False, "axes.spines.right": False})
labels = sorted(p.parent.name for p in (REPO / "results/multi_eval").glob("*/summary.json"))
S = {l: json.load(open(REPO / "results/multi_eval" / l / "summary.json")) for l in labels}
G = {l: [json.loads(x) for x in open(REPO / "results/multi_eval" / l / "graded.jsonl")] for l in labels}
def arm(l): return l.split("-")[0]
def step(l): return l.split("-", 1)[1] if "-" in l else ""
def mean(xs): xs = [x for x in xs if x is not None]; return st.mean(xs) if xs else None
def wald(p, n, z=1.2816): return (z * (p * (1 - p) / n) ** 0.5) if n and p is not None else None
def rate(l, suite, level, held=None, ok_only=True):
    gs = [g for g in G[l] if g["suite"] == suite and g["level"] == level and (held is None or g["held_out"] == held) and (g["think_status"] == "ok" or not ok_only)]
    v = [g["joint"] for g in gs if g["joint"] is not None]; return (mean(v), len(v))
md = ["# Multi-constraint SFT: results\n", f"*Generated by `scripts/report_multi.py` from {len(labels)} evaluated checkpoint(s): {', '.join(labels)}.*\n"]
P = md.append
for suite, name in (("reasonif_multi", "ReasonIF-side (in-distribution constraint set)"), ("cotcontrol_multi", "CoTControl-side (transfer)")):
    P(f"\n## {name}: joint binary compliance (all constraints satisfied), % of gradeable rollouts\n")
    cols = ["singles", "pairs (seen)", "pairs (held-out)", "triples (seen)", "triples (held-out)"] if suite == "reasonif_multi" else ["singles", "pairs", "triples"]
    P("| checkpoint | " + " | ".join(cols) + " | accuracy | truncated |"); P("|---|" + "---:|" * (len(cols) + 2))
    for l in labels:
        cells = []
        if suite == "reasonif_multi":
            for lvl, held in ((1, None), (2, False), (2, True), (3, False), (3, True)):
                r, n = rate(l, suite, lvl, held); cells.append(f"{100*r:.1f} ± {100*wald(r,n):.1f} (n {n})" if r is not None else "—")
        else:
            for lvl in (1, 2, 3):
                r, n = rate(l, suite, lvl); cells.append(f"{100*r:.1f} ± {100*wald(r,n):.1f} (n {n})" if r is not None else "—")
        gs = [g for g in G[l] if g["suite"] == suite]; acc = mean([g["correct"] for g in gs]); tr = mean([g["truncated"] for g in gs])
        P(f"| {l} | " + " | ".join(cells) + f" | {100*acc:.0f} % | {100*tr:.0f} % |")
    P(f"\n![joint compliance by level]({'figures/multi_joint_' + suite + '.png'})\n")
    # per-condition table
    P(f"\n### Per condition (joint %, gradeable n)\n")
    conds = sorted({m for l in labels for m in S[l]["conditions"] if S[l]["conditions"][m]["suite"] == suite}, key=lambda m: (S[labels[0]]["conditions"].get(m, {}).get("level", 9), m))
    P("| condition | " + " | ".join(labels) + " |"); P("|---|" + "---:|" * len(labels))
    for m in conds:
        row = []
        for l in labels:
            c = S[l]["conditions"].get(m); row.append(f"{100*c['joint_binary']:.0f} ({c['gradeable']})" if c and c["joint_binary"] is not None else "—")
        P(f"| {m}{' †' if any(S[l]['conditions'].get(m,{}).get('held_out') for l in labels) else ''} | " + " | ".join(row) + " |")
    P("\n† held out of training in every arm.\n")
    # per-constraint binary across levels (does compliance per constraint drop as k grows?)
    P(f"\n### Per-constraint binary compliance by level (%, averaged over conditions containing the constraint)\n")
    cons = sorted({c for l in labels for m, cd in S[l]["conditions"].items() if cd["suite"] == suite for c in cd["per_binary"]})
    P("| checkpoint | constraint | k=1 | k=2 | k=3 |"); P("|---|---|---:|---:|---:|")
    for l in labels:
        for c in cons:
            vals = []
            for lvl in (1, 2, 3):
                xs = [cd["per_binary"][c] for cd in S[l]["conditions"].values() if cd["suite"] == suite and cd["level"] == lvl and c in cd["per_binary"] and cd["per_binary"][c] is not None]
                vals.append(f"{100*st.mean(xs):.0f}" if xs else "—")
            P(f"| {l} | {c} | " + " | ".join(vals) + " |")
    # figure: joint by level per arm (step-final preferred), lines per arm
    fig, ax = plt.subplots(figsize=(7.5, 4), dpi=150)
    for l in labels:
        pts = [(lvl, rate(l, suite, lvl)[0]) for lvl in (1, 2, 3)]; pts = [(x, 100 * y) for x, y in pts if y is not None]
        if pts: ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=ARMC.get(arm(l), INK2), ls="-" if "final" in l or l == "base" else "--", markeredgecolor=SURF, label=l)
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(["1 constraint", "2", "3"]); ax.set_ylabel("joint compliance, %", color=INK2); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
    ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.14)); ax.set_title(f"{name}: joint compliance vs number of constraints\nsolid = step-final (~915 examples), dashed = step-60 (240 examples); colour = arm", loc="left", fontsize=10.5, color=INK)
    ax.set_ylim(0, max(ax.get_ylim()[1], 1) * 1.05); fig.tight_layout(); fig.savefig(REPO / f"figures/multi_joint_{suite}.png", bbox_inches="tight"); plt.close(fig)
# three ReasonIF-side figures: seen-only, held-out-only, and T3 seen vs held-out
def lvl_fig(fname, title, xt, held_sel, only_labels=None, two_series=False):
    fig, ax = plt.subplots(figsize=(7.5, 4), dpi=150)
    for l in labels:
        if only_labels and l not in only_labels: continue
        series = [("seen", False, "-"), ("held-out", True, ":")] if two_series else [(None, held_sel, "-" if "final" in l or l == "base" else "--")]
        for name_, held, ls in series:
            pts = []
            for lvl in (1, 2, 3):
                if lvl == 1 and held is True: continue  # singles are all seen
                r = rate(l, "reasonif_multi", lvl, (None if lvl == 1 else held))[0]
                if r is not None: pts.append((lvl, 100 * r))
            lab = f"{l} ({name_})" if name_ else l
            col = ARMC.get(arm(l), INK2) if not two_series else ("#104281" if "final" in l else "#86b6ef")
            ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=col, ls=ls, markeredgecolor=SURF, label=lab)
    ax.set_xticks([1, 2, 3]); ax.set_xticklabels(xt); ax.set_ylabel("joint compliance, %", color=INK2); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
    ax.legend(frameon=False, fontsize=8.5, ncol=4 if two_series else 5, loc="upper center", bbox_to_anchor=(0.5, -0.2)); ax.set_ylim(0, max(ax.get_ylim()[1], 1) * 1.05)
    ax.set_title(title, loc="left", fontsize=10.5, color=INK); fig.tight_layout(); fig.savefig(REPO / f"figures/{fname}", bbox_inches="tight"); plt.close(fig)
lvl_fig("multi_joint_reasonif_seen.png", "ReasonIF-side: combinations that appeared in training (10 of 14 pairs, 12 of 16 triples)\nsolid = step-final, dashed = step-60; colour = arm", ["1 constraint", "2 (seen pairs)", "3 (seen triples)"], False)
lvl_fig("multi_joint_reasonif_heldout.png", "ReasonIF-side: combinations never seen in training (4 pairs, 4 triples)\nsolid = step-final, dashed = step-60; colour = arm", ["1 constraint\n(reference, all seen)", "2 (held-out pairs)", "3 (held-out triples)"], True)
lvl_fig("multi_joint_reasonif_T3_seen_vs_heldout.png", "Triples arm (T3): seen vs held-out combinations\nsolid = seen, dotted = held-out; dark = step-final, light = step-60", ["1 constraint", "2", "3"], None, only_labels=["T3-step-60", "T3-step-final"], two_series=True)
for fn, cap in (("multi_joint_reasonif_seen.png", "seen combinations only"), ("multi_joint_reasonif_heldout.png", "held-out combinations only"), ("multi_joint_reasonif_T3_seen_vs_heldout.png", "T3: seen vs held-out")):
    k = "\n## CoTControl-side (transfer): joint binary compliance (all constraints satisfied), % of gradeable rollouts\n"; md.insert(md.index(k) if k in md else len(md), f"\n![{cap}](figures/{fn})\n")
(REPO / "MULTI_CONSTRAINT_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote MULTI_CONSTRAINT_RESULTS.md and figures for", labels)
