#!/usr/bin/env python3
"""Tables and figures for the Qwen3-8B multi-constraint experiment (QWEN3_8B_PLAN.md).

Reads results/qwen3_8b/eval/<label>/graded.jsonl for base, S1-60, S1-final, T3-60, T3-final, Q5-final and the
Qwen3.5-9B summaries in results/multi_eval/ for the cross-model comparison. Writes QWEN3_8B_RESULTS.md and
figures/q3_8b_*.png.
"""
from __future__ import annotations
import json, math, statistics as st, sys
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[1]
SURF, INK, INK2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"
C = {"base": "#c3c2b7", "S1": "#86b6ef", "T3": "#104281", "Q5": "#eb6834"}
LABS = ["base", "S1-60", "S1-final", "T3-60", "T3-final", "Q5-final"]
FINAL = ["base", "S1-final", "T3-final", "Q5-final"]
plt.rcParams.update({"figure.facecolor": SURF, "axes.facecolor": SURF, "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED,
                     "font.size": 9.5, "axes.spines.top": False, "axes.spines.right": False, "savefig.dpi": 150, "savefig.facecolor": SURF})

def arm(l): return l.split("-")[0]
G = {l: [json.loads(x) for x in open(REPO / f"results/qwen3_8b/eval/{l}/graded.jsonl")] for l in LABS}
def rows(l, suite, level=None, held=None, mode=None):
    return [r for r in G[l] if r["suite"] == suite and (level is None or r["level"] == level) and (held is None or bool(r["held_out"]) == held) and (mode is None or r["constraints"][0] == mode)]
def joint(rs):
    ok = [r for r in rs if r["think_status"] == "ok" and r["joint"] is not None]
    if not ok: return None, 0
    p = sum(r["joint"] for r in ok) / len(ok); return p, len(ok)
def ci80(p, n): return 1.2816 * math.sqrt(p * (1 - p) / n) if n else 0
def per_bin(rs, m):
    v = [r["per_binary"][m] for r in rs if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def per_cont(rs, m):
    v = [r["per_continuous"][m] for r in rs if r["think_status"] == "ok" and r["per_continuous"].get(m) is not None]; return (sum(v) / len(v), len(v)) if v else (None, 0)
def acc(rs): return sum(bool(r["correct"]) for r in rs) / len(rs) if rs else None
def cont_macro(l, level=1, exclude=None):
    """CoTControl continuous, macro over modes (k=1) — comparable to MULTI_CONSTRAINT_FINDINGS.md finding 4b."""
    vals = []
    for m in sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)}):
        if m == exclude: continue
        v, n = per_cont(rows(l, "cotcontrol_multi", level, mode=m), m)
        if v is not None: vals.append(v)
    return sum(vals) / len(vals) if vals else None

md = ["# Multi-constraint SFT on Qwen3-8B: results\n", "*Generated by `scripts/report_qwen3_8b.py`. Joint = every constraint in the prompt satisfied, binary, % of gradeable (closed think block) rollouts; ± = 80 % Wald interval.*\n"]
P = md.append
def pct(p, n): return "—" if p is None else f"{100*p:.1f} ± {100*ci80(p,n):.1f}"

P("\n## Joint binary compliance by level\n")
P("| suite | level | " + " | ".join(LABS) + " |"); P("|---|---|" + "---:|" * len(LABS))
for suite, name in (("reasonif_multi", "ReasonIF"), ("cotcontrol_multi", "CoTControl")):
    for lvl in (1, 3, 5, 6):
        for held in (None, True):
            cells = []
            for l in LABS:
                rs = rows(l, suite, lvl, held); p, n = joint(rs); cells.append(pct(p, n) if rs else "—")
            if all(c == "—" for c in cells): continue
            P(f"| {name} | k={lvl}{' held-out' if held else ''} | " + " | ".join(cells) + " |")
P("\n## Accuracy on the k=1 prompts (%)\n")
P("| suite | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for suite, name in (("reasonif_multi", "ReasonIF"), ("cotcontrol_multi", "CoTControl")):
    P(f"| {name} | " + " | ".join(f"{100*acc(rows(l, suite, 1)):.0f}" for l in LABS) + " |")
P("\n## Per-constraint compliance on single-constraint prompts (binary % / continuous)\n")
P("| constraint | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
for suite in ("reasonif_multi", "cotcontrol_multi"):
    for m in sorted({r["constraints"][0] for r in rows("base", suite, 1)}):
        cells = []
        for l in LABS:
            b, nb = per_bin(rows(l, suite, 1, mode=m), m); c, nc = per_cont(rows(l, suite, 1, mode=m), m)
            cells.append(("—" if b is None else f"{100*b:.0f}") + ("" if c is None else f" / {c:.2f}"))
        P(f"| {suite[:3]}/{m} | " + " | ".join(cells) + " |")
P("\n## CoTControl continuous macro over the ten modes (k=1)\n")
P("| | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
P("| all ten modes | " + " | ".join(f"{cont_macro(l):.2f}" for l in LABS) + " |")
P("| excluding uppercase_thinking | " + " | ".join(f"{cont_macro(l, exclude='uppercase_thinking'):.2f}" for l in LABS) + " |")
P("\n## Per-constraint binary by number of rules in the prompt (ReasonIF, %, step-final arms)\n")
P("| constraint | " + " | ".join(f"{l} k=1/3/5" for l in FINAL) + " |"); P("|---|" + "---:|" * len(FINAL))
for m in sorted({r["constraints"][0] for r in rows("base", "reasonif_multi", 1)}):
    cells = []
    for l in FINAL:
        vals = []
        for lvl in (1, 3, 5):
            v = [r["per_binary"][m] for r in rows(l, "reasonif_multi", lvl) if r["think_status"] == "ok" and r["per_binary"].get(m) is not None]
            vals.append(f"{100*sum(v)/len(v):.0f}" if v else "—")
        cells.append(" / ".join(vals))
    P(f"| {m} | " + " | ".join(cells) + " |")
P("\n## Per-mode binary inside CoTControl combinations (%, gradeable rollouts containing the mode)\n")
P("| level | checkpoint | " + " | ".join(m for m in sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)})) + " |")
modes_cc = sorted({r["constraints"][0] for r in rows("base", "cotcontrol_multi", 1)}); P("|---|---|" + "---:|" * len(modes_cc))
for lvl in (3, 6):
    for l in FINAL:
        per = defaultdict(list)
        for r in rows(l, "cotcontrol_multi", lvl):
            if r["think_status"] != "ok": continue
            for m, b in r["per_binary"].items():
                if b is not None: per[m].append(b)
        P(f"| k={lvl} | {l} | " + " | ".join(f"{100*sum(per[m])/len(per[m]):.0f}" if per[m] else "—" for m in modes_cc) + " |")
P("\n## Trace status\n")
P("| | " + " | ".join(LABS) + " |"); P("|---|" + "---:|" * len(LABS))
P("| rollouts | " + " | ".join(str(len(G[l])) for l in LABS) + " |")
P("| truncated at 32k | " + " | ".join(str(sum(r['truncated'] for r in G[l])) for l in LABS) + " |")
P("| empty think block | " + " | ".join(str(sum(r['think_status'] == 'empty' for r in G[l])) for l in LABS) + " |")
P("| median completion tokens, CoTControl k=1 | " + " | ".join(str(int(st.median(r['completion_tokens'] for r in rows(l, 'cotcontrol_multi', 1)))) for l in LABS) + " |")

# ---------------------------------------------------------------- figures
def style(ax): ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)

# Fig 1: ReasonIF joint by level, step-final arms, seen vs held-out at k=3
fig, ax = plt.subplots(figsize=(7.5, 4))
for l in FINAL:
    pts = [(lvl, 100 * joint(rows(l, "reasonif_multi", lvl))[0]) for lvl in (1, 3, 5)]
    ax.plot([p[0] for p in pts], [p[1] for p in pts], marker="o", ms=7, lw=2, color=C[arm(l)], markeredgecolor=SURF, label=l)
    ph, nh = joint(rows(l, "reasonif_multi", 3, held=True))
    if ph is not None: ax.plot([3.12], [100 * ph], marker="D", ms=6, color=C[arm(l)], ls="", markeredgecolor=SURF)
ax.plot([], [], marker="D", ms=6, color=INK2, ls="", label="◆ held-out triples only"); ax.set_xticks([1, 3, 5]); ax.set_xticklabels(["1 constraint", "3", "5"]); ax.set_ylabel("joint compliance, %"); style(ax)
ax.set_title("Qwen3-8B, ReasonIF-side: joint binary compliance vs number of constraints (step-final)\nQ5 was trained on 5-constraint prompts only; ◆ = the 4 held-out triples", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.14)); ax.set_ylim(0, 60); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_joint_reasonif.png", bbox_inches="tight"); plt.close(fig)

# Fig 2: CoTControl k=1 joint binary per checkpoint (bars), with the k=3/k=6 zeros noted
fig, ax = plt.subplots(figsize=(7.5, 3.8))
vals = [joint(rows(l, "cotcontrol_multi", 1)) for l in LABS]
ax.bar(range(len(LABS)), [100 * v for v, _ in vals], color=[C[arm(l)] for l in LABS], width=0.62, edgecolor=SURF)
for i, (v, n) in enumerate(vals): ax.text(i, 100 * v + 0.4, f"{100*v:.1f}", ha="center", fontsize=9, color=INK2)
ax.set_xticks(range(len(LABS))); ax.set_xticklabels(LABS); ax.set_ylabel("joint compliance, %"); style(ax); ax.set_ylim(0, 16)
ax.set_title("Qwen3-8B, CoTControl-side transfer: joint binary compliance on single-mode prompts\n(k=3 and k=6 prompts: 0 % for every checkpoint)", loc="left", fontsize=10.5, color=INK)
fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_joint_cotcontrol_k1.png", bbox_inches="tight"); plt.close(fig)

# Fig 3: CoTControl per-mode binary on singles, grouped bars
fig, ax = plt.subplots(figsize=(11, 4.2))
w = 0.8 / len(LABS)
for j, l in enumerate(LABS):
    ys = [100 * (per_bin(rows(l, "cotcontrol_multi", 1, mode=m), m)[0] or 0) for m in modes_cc]
    ax.bar([i + (j - (len(LABS) - 1) / 2) * w for i in range(len(modes_cc))], ys, width=w, color=C[arm(l)], edgecolor=SURF, alpha=1 if "final" in l or l == "base" else 0.55, label=l)
ax.set_xticks(range(len(modes_cc))); ax.set_xticklabels([m.replace("_", "\n") for m in modes_cc], fontsize=8.5); ax.set_ylabel("binary compliance, %"); style(ax)
ax.set_title("Qwen3-8B, CoTControl single-mode prompts: binary compliance per mode (lighter = step-60)", loc="left", fontsize=10.5, color=INK)
ax.legend(frameon=False, fontsize=8.5, ncol=6, loc="upper center", bbox_to_anchor=(0.5, -0.22)); fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_cotcontrol_modes.png", bbox_inches="tight"); plt.close(fig)

# Fig 4: CoTControl continuous macro, all modes vs excluding uppercase
fig, axes = plt.subplots(1, 2, figsize=(10, 3.8), sharey=True)
for ax, ex, ttl in zip(axes, (None, "uppercase_thinking"), ("all ten modes", "excluding uppercase_thinking")):
    ys = [cont_macro(l, exclude=ex) for l in LABS]
    ax.bar(range(len(LABS)), ys, color=[C[arm(l)] for l in LABS], width=0.62, edgecolor=SURF)
    for i, y in enumerate(ys): ax.text(i, y + 0.01, f"{y:.2f}", ha="center", fontsize=9, color=INK2)
    ax.set_xticks(range(len(LABS))); ax.set_xticklabels(LABS, fontsize=8.5); style(ax); ax.set_title(ttl, loc="left", fontsize=10, color=INK)
axes[0].set_ylabel("continuous compliance, macro over modes"); axes[0].set_ylim(0, 0.7)
fig.suptitle("Qwen3-8B, CoTControl single-mode prompts: continuous (graded) compliance", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.tight_layout(); fig.savefig(REPO / "figures/q3_8b_cotcontrol_continuous.png", bbox_inches="tight"); plt.close(fig)

# Fig 5: step-60 vs step-final on k=1, both suites, S1 and T3 (dumbbells)
fig, axes = plt.subplots(1, 2, figsize=(10, 3.2), sharey=True)
for ax, suite, ttl in zip(axes, ("reasonif_multi", "cotcontrol_multi"), ("ReasonIF k=1 (in-domain)", "CoTControl k=1 (transfer)")):
    for i, a in enumerate(("S1", "T3")):
        b = 100 * joint(rows("base", suite, 1))[0]; y60 = 100 * joint(rows(f"{a}-60", suite, 1))[0]; yf = 100 * joint(rows(f"{a}-final", suite, 1))[0]
        ax.plot([y60, yf], [i, i], color=GRID, lw=3, zorder=1); ax.plot([y60], [i], "o", color="#c3c2b7", ms=9, markeredgecolor=SURF, zorder=2); ax.plot([yf], [i], "o", color=C[a], ms=9, markeredgecolor=SURF, zorder=3)
        ax.axvline(b, color=MUTED, lw=1, ls=":")
    ax.set_yticks([0, 1]); ax.set_yticklabels(["S1", "T3"]); ax.set_xlabel("joint compliance, %"); ax.set_title(ttl, loc="left", fontsize=10, color=INK); ax.xaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
axes[0].set_ylim(-0.6, 1.6)
fig.legend(handles=[plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#c3c2b7", markeredgecolor=SURF, label="step-60 (240 examples)"), plt.Line2D([0], [0], marker="o", ls="", ms=8, color="#2a78d6", markeredgecolor=SURF, label="step-final (~915; colour = arm)"), plt.Line2D([0], [0], ls=":", color=MUTED, label="base")], frameon=False, loc="lower center", bbox_to_anchor=(0.5, -0.06), ncol=3, fontsize=9)
fig.suptitle("Qwen3-8B: step-60 vs step-final on single-constraint prompts", x=0.01, ha="left", fontsize=10.5, color=INK); fig.tight_layout(rect=(0, 0.05, 1, 0.94)); fig.savefig(REPO / "figures/q3_8b_step60_vs_final.png", bbox_inches="tight"); plt.close(fig)

# Fig 6: cross-model comparison, S1 and T3 step-final vs base, ReasonIF k=1/k=3 and CoTControl k=1 (binary) + continuous macro
S35 = {l: json.load(open(REPO / f"results/multi_eval/{l}/summary.json")) for l in ("base", "S1-step-final", "T3-step-final")}
def s35(l, key): return S35[l].get(key)
def s35_cont(l):
    c = S35[l]["conditions"]; vals = [v["per_continuous"][k] for m, v in c.items() if v["suite"] == "cotcontrol_multi" and v["level"] == 1 for k in v["per_continuous"] if v["per_continuous"][k] is not None]
    return sum(vals) / len(vals)
panels = [("ReasonIF k=1, joint %", lambda l: 100 * s35(l, "reasonif_multi/k1/joint_macro"), lambda l: 100 * joint(rows(l, "reasonif_multi", 1))[0]),
          ("ReasonIF k=3, joint %", lambda l: 100 * s35(l, "reasonif_multi/k3/joint_macro"), lambda l: 100 * joint(rows(l, "reasonif_multi", 3))[0]),
          ("CoTControl k=1, joint %", lambda l: 100 * s35(l, "cotcontrol_multi/k1/joint_macro"), lambda l: 100 * joint(rows(l, "cotcontrol_multi", 1))[0]),
          ("CoTControl k=1, continuous macro", s35_cont, lambda l: cont_macro(l))]
fig, axes = plt.subplots(1, 4, figsize=(13, 3.6))
for ax, (ttl, f35, f38) in zip(axes, panels):
    arms = ["base", "S1", "T3"]; x = range(3)
    v35 = [f35({"base": "base", "S1": "S1-step-final", "T3": "T3-step-final"}[a]) for a in arms]; v38 = [f38({"base": "base", "S1": "S1-final", "T3": "T3-final"}[a]) for a in arms]
    ax.bar([i - 0.19 for i in x], v35, width=0.36, color=[C[a] for a in arms], alpha=0.45, edgecolor=SURF, label="Qwen3.5-9B" if ax is axes[0] else None)
    ax.bar([i + 0.19 for i in x], v38, width=0.36, color=[C[a] for a in arms], edgecolor=SURF, label="Qwen3-8B" if ax is axes[0] else None)
    for i in x: ax.text(i - 0.19, v35[i], f"{v35[i]:.0f}" if "joint" in ttl else f"{v35[i]:.2f}", ha="center", va="bottom", fontsize=8, color=MUTED); ax.text(i + 0.19, v38[i], f"{v38[i]:.0f}" if "joint" in ttl else f"{v38[i]:.2f}", ha="center", va="bottom", fontsize=8, color=INK2)
    ax.set_xticks(list(x)); ax.set_xticklabels(arms); ax.set_title(ttl, loc="left", fontsize=10, color=INK); style(ax)
fig.suptitle("Same constraint set, same recipe, two models: Qwen3.5-9B (faded) vs Qwen3-8B (solid), step-final", x=0.01, ha="left", fontsize=10.5, color=INK)
fig.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, -0.04), ncol=2, fontsize=9); fig.tight_layout(rect=(0, 0.04, 1, 0.93)); fig.savefig(REPO / "figures/q3_8b_vs_qwen35.png", bbox_inches="tight"); plt.close(fig)

P("\n## Figures\n")
for f, cap in (("q3_8b_joint_reasonif", "ReasonIF joint by level"), ("q3_8b_joint_cotcontrol_k1", "CoTControl k=1 joint"), ("q3_8b_cotcontrol_modes", "CoTControl per-mode singles"),
               ("q3_8b_cotcontrol_continuous", "CoTControl continuous macro"), ("q3_8b_step60_vs_final", "step-60 vs step-final"), ("q3_8b_vs_qwen35", "Qwen3.5-9B vs Qwen3-8B")):
    P(f"![{cap}](figures/{f}.png)\n")
(REPO / "QWEN3_8B_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote QWEN3_8B_RESULTS.md and 6 figures")
