#!/usr/bin/env python3
"""All 30 never-seen constraints (IFBench-derived, both batches) for base and Q5 (+ S1 and T3-60 on batch 1).
Writes NEVER_SEEN_RESULTS.md and figures/never_seen_all.png."""
from __future__ import annotations
import json, sys
from collections import defaultdict
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
REPO = Path(__file__).resolve().parents[1]; sys.path.insert(0, str(REPO / "src")); EV = REPO / "results/unlearn/eval"
from cotctl.ifbench_eval import IFB, IFB2, ALL
SURF, INK, INK2, MUTED, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9"
plt.rcParams.update({"figure.facecolor": SURF, "axes.facecolor": SURF, "axes.edgecolor": GRID, "axes.labelcolor": INK2, "xtick.color": MUTED, "ytick.color": MUTED, "font.size": 9.5, "axes.spines.top": False, "axes.spines.right": False, "savefig.dpi": 150, "savefig.facecolor": SURF})
SRC = {"base": ["base", "base-ifb2"], "S1": ["S1-ifb"], "T3-60": ["T3-60-ifb"], "Q5": ["Q5", "Q5-ifb2"]}
def load(labels):
    d = defaultdict(list)
    for l in labels:
        p = EV / l / "graded.jsonl"
        if not p.exists(): continue
        for x in open(p):
            r = json.loads(x)
            if r["suite"] != "ifbench" or r["think_status"] != "ok": continue
            c = r["constraints"][0]; t = r["mode"].split(":")[-1]; d[(c, t)].append((r["per_binary"][c], r["per_continuous"][c]))
    return d
D = {k: load(v) for k, v in SRC.items()}
def bin_(d, c, t=None):
    v = [x for (cc, tt), xs in d.items() if cc == c and (t is None or tt == t) for x in xs]; return (100 * sum(b for b, _ in v) / len(v), sum(x for _, x in v) / len(v), len(v)) if v else (None, None, 0)
order = list(IFB) + list(IFB2)
md = ["# Never-seen constraints: base vs Q5 (30 IFBench-derived rules, both templates)\n", "*Binary %, continuous mean; 20 prompts per constraint per template. Batch 1 (first ten) also has S1-final and T3-60. Generated by `scripts/report_never_seen.py`.*\n",
      "\n| constraint | granularity | base rif | base cc | Q5 rif | Q5 cc | S1 rif/cc | T3-60 rif/cc |", "|---|---|---:|---:|---:|---:|---:|---:|"]
def cell(d, c, t): b, x, n = bin_(d, c, t); return "—" if b is None else f"{b:.0f} / {x:.2f}"
for c in order:
    md.append(f"| {c} | {ALL[c]['granularity']} | {cell(D['base'], c, 'rif')} | {cell(D['base'], c, 'cc')} | {cell(D['Q5'], c, 'rif')} | {cell(D['Q5'], c, 'cc')} | {cell(D['S1'], c, 'rif')} · {cell(D['S1'], c, 'cc')} | {cell(D['T3-60'], c, 'rif')} · {cell(D['T3-60'], c, 'cc')} |")
def pooled(d): v = [x for xs in d.values() for x in xs]; return 100 * sum(b for b, _ in v) / len(v), sum(x for _, x in v) / len(v), len(v)
md.append("\nPooled over all 30 constraints and both templates: " + "; ".join(f"{k} {pooled(D[k])[0]:.1f} % binary, {pooled(D[k])[1]:.3f} continuous (n={pooled(D[k])[2]})" for k in ("base", "Q5")) + ".")
# figure: Q5 vs base, binary (templates pooled), 30 constraints, sorted by Q5-base gap
gaps = sorted(order, key=lambda c: -((bin_(D["Q5"], c)[0] or 0) - (bin_(D["base"], c)[0] or 0)))
fig, ax = plt.subplots(figsize=(13, 4.6)); w = 0.4
for j, (k, col) in enumerate((("base", "#c3c2b7"), ("Q5", "#eb6834"))):
    ys = [bin_(D[k], c)[0] or 0 for c in gaps]
    ax.bar([i + (j - 0.5) * w for i in range(len(gaps))], ys, width=w, color=col, edgecolor=SURF, label=k)
ax.set_xticks(range(len(gaps))); ax.set_xticklabels([c.replace("_", "\n") for c in gaps], fontsize=7); ax.set_ylabel("binary compliance, % (both templates pooled)"); ax.yaxis.grid(True, color=GRID, lw=1); ax.set_axisbelow(True); ax.tick_params(length=0); ax.spines["left"].set_visible(False)
ax.set_title("Q5 vs base on 30 constraints that were in no training prompt (sorted by Q5 − base)", loc="left", fontsize=10.5, color=INK); ax.legend(frameon=False, fontsize=9, loc="upper right")
fig.tight_layout(); fig.savefig(REPO / "figures/never_seen_all.png", bbox_inches="tight"); plt.close(fig)
md.append("\n![never-seen, all 30](figures/never_seen_all.png)\n")
(REPO / "NEVER_SEEN_RESULTS.md").write_text("\n".join(md), encoding="utf-8"); print("wrote NEVER_SEEN_RESULTS.md and figures/never_seen_all.png")
